foo:
  outputs:
    dev:
      database: awsdatacatalog
      region_name: eu-west-2
      s3_data_dir: s3://foo-athena-query-result/data
      s3_staging_dir: s3://foo-athena-query-result/staging
      schema: dbt
      threads: 1
      type: athena
  target: dev
